### ISSUE TITLE
Problems encountered during use

### ISSUE THREAD

**Issue by xue09876** [HaotianZhangAI4Science/ResGen#11]
Hello, I encountered the problem "OverflowError: can't convert negative int to unsigned" while using Resgen. How can I resolve it? Thank you for your help.
C:\Users\Administer\.conda\envs\xxl\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
Start to generate in the ./examples/4iiy.pdb
C:\Users\Administer\.conda\envs\xxl\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "gen.py", line 217, in <module>
    rdmol = reconstruct_from_generated_with_edges(data_next)
  File "E:\Desktop\AI\ResGen-main\utils\reconstruct.py", line 70, in reconstruct_from_generated_with_edges
    Chem.SanitizeMol(rd_mol, Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE^Chem.SANITIZE_SETAROMATICITY)
OverflowError: can't convert negative int to unsigned

**Comment by Ca1iber** [comment]
same, have u fixed it yet?

**Comment by HaotianZhangAI4Science** [comment]
Sorry for the late response! That's weird. From my experience, I think it is the inconsistency of the rdkit. Please use my original version, rdkit=2022.03.5!
