### ISSUE TITLE
Installation issues and a test run

### ISSUE THREAD

**Issue by ryao-mdanderson** [HaotianZhangAI4Science/ResGen#12]
Dear ResGen author:

I attempted to install pytorch, cuda version as you suggested in both miniforge3 and miniconda3, hit issues that packages will be upgrade or downgrade. 

Use miniforge3 installation as an example:
(resgen) [ryao@gdragon001 ~]$ conda list
# packages in environment at /rsrch3/home/itops/ryao/miniforge3/envs/resgen:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
aiohappyeyeballs          2.3.5              pyhd8ed1ab_0    conda-forge
aiohttp                   3.10.3           py38h2019614_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
biopython                 1.83             py38h01eb140_0    conda-forge
blas                      2.123                      blis    conda-forge
blas-devel                3.9.0           23_linux64_blis    conda-forge
blis                      0.9.0                h4ab18f5_2    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0            py38h17151c0_1    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.17.0           py38heb5c249_0    conda-forge
chardet                   5.2.0            py38h578d9bd_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.1            py38h7f3f72f_1    conda-forge
cuda-version              11.6                 hca96458_3    conda-forge
cudatoolkit               11.6.2              hfc3e2af_13    conda-forge
cudnn                     8.9.7.29             hbc23b4c_3    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
easydict                  1.9                        py_0    conda-forge
expat                     2.6.2                h59595ed_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1           py38h2019614_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
frozenlist                1.4.1            py38h01eb140_0    conda-forge
fsspec                    2024.6.1           pyhff2d567_0    conda-forge
greenlet                  3.0.3            py38h17151c0_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-resources       6.4.0              pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py38h7f3f72f_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           23_linux64_blis    conda-forge
libboost                  1.84.0               h0ccab89_5    conda-forge
libboost-python           1.84.0           py38haa4b4a7_5    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           23_linux64_blis    conda-forge
libdeflate                1.21                 h4bc722e_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libglib                   2.80.3               h315aac3_2    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libhwloc                  2.11.1          default_hecaa2ac_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           6_ha36c22a_netlib    conda-forge
liblapacke                3.9.0           6_ha36c22a_netlib    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     16.4                 h482b261_0    conda-forge
libprotobuf               3.21.12              hfc55251_2    conda-forge
librdkit                  2024.03.5            h79cfef2_3    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtiff                   4.6.0                h46a8edc_4    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.48.0               hd590300_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hd590300_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
llvm-openmp               18.1.8               hf5423f3_0    conda-forge
magma                     2.5.4                hc72dce7_4    conda-forge
markupsafe                2.1.5            py38h01eb140_0    conda-forge
matplotlib-base           3.7.3            py38h58ed7fa_0    conda-forge
mkl                       2022.2.1         h6508926_16999    conda-forge
mkl-devel                 2022.2.1         ha957f24_16999    conda-forge
mkl-include               2022.2.1         ha957f24_16999    conda-forge
multidict                 6.0.5            py38h01eb140_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nccl                      2.22.3.1             hee583db_1    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
ninja                     1.12.1               h297d8ca_0    conda-forge
numpy                     1.24.4           py38h59b608b_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3            py38h01efb38_1    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pillow                    10.4.0           py38h2bc05a7_0    conda-forge
pip                       24.2               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
pooch                     1.8.2              pyhd8ed1ab_0    conda-forge
psutil                    6.0.0            py38hfb59056_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycairo                   1.26.1           py38he403b34_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyg                       2.5.2           py38_torch_1.12.0_cu116    pyg
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.19          hd12c33a_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-lmdb               1.5.1            py38h79ccf07_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      4_cp38    conda-forge
pytorch                   1.12.1          cuda112py38hd94e077_201    conda-forge
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2            py38h2019614_0    conda-forge
rdkit                     2024.03.5        py38h890d753_3    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reportlab                 4.2.2            py38hfb59056_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
scikit-learn              1.3.2            py38ha25d942_2    conda-forge
scipy                     1.10.1           py38h59b608b_3    conda-forge
setuptools                72.1.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.6.1                h3400bea_1    conda-forge
sqlalchemy                2.0.32           py38h2019614_0    conda-forge
tbb                       2021.12.0            h434a139_3    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.66.5             pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
unicodedata2              15.1.0           py38h01eb140_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.9.4            py38h01eb140_0    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h4ab18f5_1    conda-forge
zstandard                 0.23.0           py38h62bed22_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
(resgen) [ryao@gdragon001 ~]$ 

To run an example, hit the message:
(resgen) [ryao@edragon037 ResGen]$ python gen.py --pdf_file ./examples/4iiy.pdb --sdf_file ./examples/4iiy_ligand.sdf --outdir ./examples/
Traceback (most recent call last):
  File "gen.py", line 19, in <module>
    from utils.feats.protein import get_protein_feature_v2
  File "/rsrch3/home/itops/ryao/ResGen/utils/feats/__init__.py", line 2, in <module>
    from .protein import parse_PDB_v2
  File "/rsrch3/home/itops/ryao/ResGen/utils/feats/protein.py", line 8, in <module>
    import torch_cluster
ModuleNotFoundError: No module named 'torch_cluster'

I have spent hours working on this without a solution, please advise.  If there is a container version of Resgen with all the dependencies, that will be great.

Regards,
Rong Yao

**Comment by HaotianZhangAI4Science** [comment]
I think the most challenging part of environment configuration is the PyG. Please first install PyG, torch, and RDKit! I think I have provided a conda-pack file that can be used directly after unzipping. Please give it a try!
