### ISSUE TITLE
Could not reproduce train.py course

### ISSUE THREAD

**Issue by wangpp010698** [HaotianZhangAI4Science/ResGen#13]
Wonderful work! I tried to reproduct the training process. But when I tried to run the commands “python train.py --config ./configs/train_res.yml --logdir logs”，ResGen failed and the errored information as follow:

[2024-09-24 12:05:05,702::train::INFO] Load checkpoint from /public/home/hhxy/wangpoints/train_186.pt
Traceback (most recent call last):
  File "train.py", line 204, in <module>
    train()
  File "train.py", line 141, in train
    best_loss = load(config.train.checkpoint_path,ckpt_name)
  File "train.py", line 114, in load
    state = torch.load(checkpoint, map_location=args.device)   
  File "/public/home/hhxy/mambaforge/envs/resgen/lib/python3.8/site-packages/torch
    with _open_file_like(f, 'rb') as opened_file:
  File "/public/home/hhxy/mambaforge/envs/resgen/lib/python3.8/site-packages/torch
    return _open_file(name_or_buffer, mode)
  File "/public/home/hhxy/mambaforge/envs/resgen/lib/python3.8/site-packages/torch
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/hhxy/wangpp/nts/train_186.pt'

Wish your reply and hope to get your guidance and explanation, thanks a million.

**Comment by HaotianZhangAI4Science** [comment]
Hi! Please make sure you put the right checkpoint file in your path!
